// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYEW6P1MFQ4n2oxF7dyXQCOhpxJ9sW4LI',
    appId: '1:791347674863:web:50d7032e95c9c0d100e51a',
    messagingSenderId: '791347674863',
    projectId: 'todoflutter-10ef9',
    authDomain: 'todoflutter-10ef9.firebaseapp.com',
    storageBucket: 'todoflutter-10ef9.firebasestorage.app',
    measurementId: 'G-J55N8M21QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBslOP4USGEtGiLFgYAXGEKPlkiHHokHg0',
    appId: '1:791347674863:android:dbba220d3189ecf200e51a',
    messagingSenderId: '791347674863',
    projectId: 'todoflutter-10ef9',
    storageBucket: 'todoflutter-10ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiFwo-PVDGCHa4axi_Og4ecsQLZIS7wIk',
    appId: '1:791347674863:ios:08bafbc6d446615c00e51a',
    messagingSenderId: '791347674863',
    projectId: 'todoflutter-10ef9',
    storageBucket: 'todoflutter-10ef9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiFwo-PVDGCHa4axi_Og4ecsQLZIS7wIk',
    appId: '1:791347674863:ios:08bafbc6d446615c00e51a',
    messagingSenderId: '791347674863',
    projectId: 'todoflutter-10ef9',
    storageBucket: 'todoflutter-10ef9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYEW6P1MFQ4n2oxF7dyXQCOhpxJ9sW4LI',
    appId: '1:791347674863:web:52c15c149eeaee4200e51a',
    messagingSenderId: '791347674863',
    projectId: 'todoflutter-10ef9',
    authDomain: 'todoflutter-10ef9.firebaseapp.com',
    storageBucket: 'todoflutter-10ef9.firebasestorage.app',
    measurementId: 'G-XTL5W7QVXG',
  );
}
